[package]
name = "web-server"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
