[package]
name = "study-rust-example"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c-kzg = "0.1.0"
# 类比于npm的包的管理方式，^
rand = "0.8.5"
