[workspace]
members = [
    "study-example",
    "minigrep",
    "hello_macro_derive",
    "web-server",
    "study-practice",
    "crypto",
    "vsock-node",
    "async-web-server",
    "redis-simple",
    "list"
]

[workspace.package]
name = "study-rust-example"
version = "0.2.2"
edition = "2021"
description = "a study example"
license = "MIT"
repository = "https://github.com/Trackerming/study-rust-example.git"
