[workspace]
members = [
    "study-example",
    "minigrep",
]

[workspace.package]
name = "study-rust-example"
version = "0.2.0"
edition = "2021"
description = "a study example"
license = "MIT"
repository = "https://github.com/Trackerming/study-rust-example.git"
