[workspace]
members = [
    "study-example",
    "minigrep",
    "hello_macro_derive",
    "web-server",
]

[workspace.package]
name = "study-rust-example"
version = "0.2.1"
edition = "2021"
description = "a study example"
license = "MIT"
repository = "https://github.com/Trackerming/study-rust-example.git"
