[package]
name = "zero_knowledge"
version.workspace = true
edition.workspace = true

[dependencies]
ecc_simple_demo = {path = "../ecc_simple_demo"}
crypto_util = {path = "../crypto_util"}
rand = "0.8.5"
