pub mod array_practice;
pub mod borrow_reference;
pub mod enum_practice;
pub mod loop_practice;
pub mod string_practice;
pub mod struct_practice;
pub mod tuple;
/// 练习的来源 https://zh.practice.rs/
pub mod var_ownership;
