[package]
name = "enc_dec"
version.workspace = true
edition.workspace = true

[dependencies]
num-bigint = "0.4.4"
num-integer = "0.1.46"
num-traits = "0.2.18"
sha2 = "0.10.8"
bitcoin_hashes = "0.14.0"
